VERSION="2.1.0"

NETWORK_PASSPHRASE="Public Global Stellar Network ; September 2015"
ASSET_METADATA_SERVER="https://api.skyhitz.io/api/assets"

ACCOUNTS=[
"GBGNRA46ZTWAO3L2QWBQBUMFKXELI3DWOB2PZAVL6YIFQQTFFQXQMQCJ",
"GCAETBNBFKVGLYFXKCLMKT6ZVHFXHRSDFSEW7ODIUJYC6R7H2QJ6OKGU"
]

[DOCUMENTATION]
ORG_NAME="Skyhitz"
ORG_URL="https://skyhitz.io"
ORG_LOGO="https://skyhitz.io/icon.png"
ORG_DESCRIPTION="Music NFTs on Stellar"
ORG_TWITTER="Skyhitz"
ORG_OFFICIAL_EMAIL="support@skyhitz.io"
ORG_SUPPORT_EMAIL="support@skyhitz.io"

[[VALIDATORS]]
ALIAS="elysium"
DISPLAY_NAME="Elysium"
HOST="elysium.skyhitz.io:11625"
PUBLIC_KEY="GDXRAFVQ4CGVWH2I3HAO457AEFUONRT6JWX4J4CNINMJXJYJW32YBOJJ"
HISTORY="https://history.elysium.skyhitz.io/"

[[VALIDATORS]]
ALIAS="venus"
DISPLAY_NAME="Venus"
HOST="venus.skyhitz.io:21625"
PUBLIC_KEY="GAM3VQ4PJQTSDSPBQYBROS36KU6JHKDEU4M5UJSAIFQS5EMDBFH6MGYB"
HISTORY="https://history.venus.skyhitz.io/"

[[VALIDATORS]]
ALIAS="praxis"
DISPLAY_NAME="Praxis"
HOST="praxis.skyhitz.io:31625"
PUBLIC_KEY="GBYBKOIG2PDL3MM7V5D5P5UB4YWJOQCAFTF3WO3B3ELNIMZEVCKNSCTN"
HISTORY="https://history.praxis.skyhitz.io/"

[[PRINCIPALS]]
name="Skyhitz"
email="hello@skyhitz.io"
twitter="skyhitz"
github="skyhitz"

